name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
      contents: write
    steps:
      - uses: actions/checkout@v2 # Checkout your repository content

      - name: Setup Node.js  # Optional: if your build process needs Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '22' # Or your desired Node.js version

      - name: Install dependencies and Build  # Optional: if your project has dependencies
        run: |
          npm install
          npm run build
          ls /home/runner/work/ -al
          ls /home/runner/work/nysds-react-demo/ -al
          ls /home/runner/work/nysds-react-demo/nysds-react-demo/ -al
          ls /home/runner/work/nysds-react-demo/nysds-react-demo/dist -al
          


      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ../dist
          github_token: ${{ secrets.GITHUB_TOKEN }}